import {Component} from "@angular/core";
import {BaseDataService} from "angular-component-service";
import {Router} from "@angular/router";

@Component({
  selector:"create-goods-form",
  template:"<base-form-component [formModel]='formModel'></base-form-component>",
  providers:[BaseDataService]
})
export class CreateGoodsFormComponentFormGroup{

  constructor(
    public baseDataService:BaseDataService,private router:Router
  ){
  }

  formModel={
      url:"goods/saveGoods.json",
      submit:(value:any)=>{
        this.submit(value);
      },
      elements:[
        /*{
          label:"商品焦点图",
          type:"array",
          prop:"goodsDetailImages",
          validate:{arrayUploadRequired:1},
          options:[
            {
              label:"",
              prop:"detailA",
              type:"upload",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailB",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailC",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailD",
              value:"",
              imgId:"",
              type:"upload",
              multiple:false,
              imageUrl:"",
              showUrl:"",
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailE",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            }
          ]
        },*/
        {
          label:"详情图片     sdfasdf",
          prop:"detailPics",
          type:"array",
          multiple:false,
          uploadClass:{myUploadStyle2:true},
          options:[
              {
                label:"",
                prop:"detailA",
                type:"upload",
                value:"",
                multiple:false,
               imageUrl:"",
               showUrl:"",
                uploadClass:{myUploadStyle2:true},
                imageConfig:{id:"imgId",url:"imageUrl",detail:"大转cvhfghdfgh盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
              },
              {
                label:"",
                prop:"detailB",
                value:"",
                type:"upload",
                multiple:false,
               imgId:"",
               imageUrl:"",
               showUrl:"",
                uploadClass:{myUploadStyle2:true},
                imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
              }
          ],
          validate:{arrayUploadRequired:1}
        }
      ]
    };

  submit(value:any){
    console.log("sub sub this.formGroup",value)
    this.baseDataService.listData({url:this.formModel.url,param:value,httpMethod:"post"}).subscribe((data:any)=>{
      console.log(data)
    },(error:any)=>{
      console.log(error);
      this.router.navigate(["lotteryList"])
    })
  }
}
