import {Component} from "@angular/core";
import {Router} from "@angular/router";
import {BaseDateChooseDirective} from "../../directive/base.date.choose";
import {BaseDataService} from "angular-component-service";

@Component({
  selector:"create-goods-form",
  template:"<base-form-component [formModel]='formModel'></base-form-component>",
  providers:[BaseDateChooseDirective,BaseDataService]
})
export class CreateGoodsFormComponent{

  constructor(
      public baseDataService:BaseDataService,private router:Router
  ){
  }

  formModel={
      url:"goods/saveGoods.json",
      submit:(value:any)=>{
        this.submit(value);
      },
      elements:[
        {
          type:"input",
          label:"商品类型",
          prop:"goodsType",
          removeValidateUrl:"",
          placeholder:"请输入商品类型",
          defaultValue:"",
          required:true,
          validate:{required:true}
        },
        {
          type:"radio",
          label:"发放范围",
          prop:"serviceRange",
          removeValidateUrl:"",
          placeholder:"商品发布范围",
          defaultValue:"1",
          required:true,
          options:[
            {label:"自动覆盖店铺",value:1},
            {label:"自定范围",value:2}
          ],
          switcher:[
            {
              prop:"goodsType",
              showValue:1
            }
          ],
          validate:{required:true}
        },
        {
          label:"选择服务范围",
          type:"baseAreaChoose",
          prop:"goodsServiceRangeDetail",
          defaultValue:"请输入商品服务范围",
          switcher:[
            {
              prop:"serviceRange",
              showValue:"2"
            }
          ]
        },
        {
          type:"select",
          label:"商品分类",
          prop:"goodsCategory",
          defaultValue:"",
          remoteInfo:{
            baseUrl:"https://testbackend.goodaa.com.cn/ejiazi-backend/",
            url:"indexPromotion/initJumpTypes.json",
            httpMethod:"post",
            param:{name:"testName",promotionType:"1"},
            convert:(data:any)=>{
                let options=[
                  {
                    label:"请选择",
                    value:""
                  }
                ];
                if(data.code=="1"&&data.data){
                  for(let key in data.data){
                    options.push({
                      label:data.data[key],
                      value:key
                    })
                  }
                }
                return options;
            }
          },
          switcher:[
            {
              prop:"sports",
              showValue:3
            }
          ],
          options:[
            {
              label:"休闲食品",
              value:"0"
            },
            {
              label:"家居日化",
              value:"1"
            }
          ],
          placeholder:"请选择分类",
          required:true,
          validate:{watchers:true}
        },
        {
          type:"input",
          label:"商品名称",
          prop:"goodsName",
          placeholder:"请输入商品名称",
          defaultValue:"",
          required:true,
          validate:{required:true,maxlength:5}
        },
        {
          type:"input",
          label:"商品原价",
          prop:"goodsOrgPrice",
          placeholder:"请输入商品原价",
          defaultValue:"",
          required:true,
          validate:{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5}
        },
        {
          type:"input",
          label:"商品现价",
          prop:"goodsCurPrice",
          placeholder:"请输入商品现价",
          defaultValue:"",
          required:true,
          validate:{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5}
        },
        {
          type:"input",
          label:"商品库存",
          prop:"goodsLib",
          placeholder:"请输入商品库存",
          defaultValue:"",
          required:true,
          validate:{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5}
        },
        {
          type:"radio",
          label:"是否限购",
          prop:"isLimit",
          placeholder:"请输入商品名称",
          defaultValue:"1",
          options:[
            {
              label:"是",
              value:"0"
            },
            {
              label:"否",
              value:"1"
            }
          ],
          required:true,
          validate:{watchers:true}
        },
        {
          type:"input",
          label:"每人限购",
          prop:"buyLimitNum",
          placeholder:"请输入商品名称",
          defaultValue:"",
          required:true,
          switcher:[
            {
              prop:"isLimit",
              showValue:"0"
            }
          ],
          validate:{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5}
        },
        {
          type:"radio",
          label:"是否包邮",
          prop:"free",
          defaultValue:"0",
          options:[
            {
              label:"包邮",
              value:"0"
            },
            {
              label:"不包邮",
              value:"1"
            }
          ],
          placeholder:"请输入商品名称",
          required:true,
          validate:{required:true}
        },
        {
          type:"select",
          label:"送达说明",
          prop:"arriveInfo",
          placeholder:"送达说明",
          defaultValue:"1",
          required:true,
          options:[
            {
              label:"半小时",
              value:"0"
            },
            {
              label:"1小时",
              value:"1"
            }
          ],
          validate:{required:true}
        },
        {
          type:"checkbox",
          label:"售后说明",
          prop:"afterSale",
          options:[
            {
              label:"7天无理由退换",
              value:"0"
            }
          ],
          placeholder:"请输入名称",
          defaultValue:"2",
          required:true,
          validate:{checkboxWatchers:true}
        },
        {
          type:"input",
          label:"商品条码",
          switcher:[{
            prop:"sex",
            showValue:"1"
          }],
          prop:"goodsQurt",
          validate:{required:true,number:"##.##",maxvalue:10,minvalue:0.5}
        },
        {
          type:"checkbox",
          label:"体育运动",
          prop:"sports",
          options:[
            {
              label:"跑步",
              value:"0"
            },
            {
              label:"健身",
              value:"1"
            },
            {
              label:"瑜伽",
              value:"2"
            },
            {
              label:"太极",
              value:"3"}
          ],
          placeholder:"请输入名称",
          defaultValue:"2",
          required:true,
          validate:{checkboxRequired:true,checkboxWatchers:true}
        },
        {
          type:"array",
          label:"活动时间",
          prop:"compSizeInnerHeight",
          options:[
            {
              label:"",
              type:"input",
              prop:"compA",
              value:"0"
            },
            {
              label:"至",
              type:"input",
              prop:"compB",
              value:"1"
            },
          ]
        },
        {
          label:"头图",
          prop:"firstPic",
          type:"upload",
          multiple:false,
          uploadClass:{myUploadStyle:true},
          require:true,
          defaultValue:"",
          imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
          validate:{required:true}
        },
        {
          label:"详情图片",
          prop:"detailPics",
          type:"array",
          multiple:false,
          uploadClass:{myUploadStyle2:true},
          options:[
            {
              label:"",
              prop:"detailA",
              type:"upload",
              value:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailB",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailC",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailD",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailE",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailF",
              type:"upload",
              value:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailG",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailH",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailI",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailJ",
              value:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            }
          ],
          validate:{arrayUploadRequired:1}
        },
        {
          label:"商品焦点图",
          type:"array",
          prop:"goodsDetailImages",
          validate:{arrayUploadRequired:1},
          options:[
            {
              label:"",
              prop:"detailA",
              type:"upload",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailB",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailC",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailD",
              value:"",
              imgId:"",
              type:"upload",
              multiple:false,
              imageUrl:"",
              showUrl:"",
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            },
            {
              label:"",
              prop:"detailE",
              value:"",
              imgId:"",
              imageUrl:"",
              showUrl:"",
              type:"upload",
              multiple:false,
              uploadClass:{myUploadStyle2:true},
              imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
            }
          ]
        },
        {
          label:"商品重量",
          type:"input",
          prop:"goodsWeight",
          validate:{required:true,number:"###.###",maxvalue:"9999.99",minvalue:"0.001",maxlength:5}
        },
        {
          label:"描述",
          type:"textarea",
          prop:"goodsDetailInfo",
          validate:{required:true}
        },
        {
          label:"商品发布",
          type:"radio",
          prop:"isPublish",
          defaultValue:"1",
          options:[
            {
              label:"放入仓库",
              value:"0"
            },
            {
              label:"立即上架",
              value:"1"
            }
          ],
          validate:{watchers:true}
        },
        {
          label:"定时上架",
          prop:"timerUpSheep",
          type:"input",
          switcher:[
            {
              prop:"isPublish",
              showValue:"0"
            }
          ],
          defaultValue:"请输入上架时间"
        },
        {
          label:"定时下架",
          prop:"timerDownSheep",
          type:"input",
          defaultValue:"请输入下架时间"
        },
        {
          label:"开始时间",
          prop:"startTimeStr",
          defaultValue:"",
          type:"date",
          chooseConfig:{
            format:'YYYY-MM-DD hh:mm:ss',
            placeholder:'请输入开始时间',
            next:0.5,
            maxelementid:'endTimeStr',
            minelementid:null
          }
        },
        {
          label:"结束时间",
          prop:"endTimeStr",
          defaultValue:"",
          type:"date",
          chooseConfig:{
            format:'YYYY-MM-DD hh:mm:ss',
            placeholder:'请输入开始时间',
            next:0,
            maxelementid:null,
            minelementid:"startTimeStr"
          }
        },
        {
          label:"活动时间",
          type:"array",
          prop:"activeTime",
          options:[
            {
              label:"",
              prop:"activeStartTimeStr",
              defaultValue:"",
              type:"date",
              value:"",
              chooseConfig:{
                format:'YYYY-MM-DD',
                placeholder:'请输入开始时间',
                next:0.5,
                maxelementid:'activeEndTimeStr',
                minelementid:null
              }
            },
            {
              label:"-",
              prop:"activeEndTimeStr",
              defaultValue:"",
              type:"date",
              value:"",
              chooseConfig:{
                format:'YYYY-MM-DD',
                placeholder:'请输入开始时间',
                next:0,
                maxelementid:null,
                minelementid:"activeStartTimeStr"
              }
            }
          ]
        }
      ]
    };

  formModel2:any={
    url:"goods/saveGoods.json",
    submit:(value:any)=>{
      this.submit(value);
    },
    elements:[
      {
        type:"input",
        label:"远程校验",
        prop:"name",
        removeValidateUrl:"",
        placeholder:"请输入名称",
        defaultValue:"",
        required:true,
        switcher:[{
          prop:"sports",
          showValue:2
        },{
          prop:"sex",
          showValue:0
        }],
        validate:{remote:true},
        override:{
          remoteValidateRequiredParam:{"name":true,name1:true},
          alias:{name:"inputName"},
          remoteService:{
            url:"goods/existName",
            httpMethod:"get",
            baseUrl:"https://testmerchant.goodaa.com.cn/ejiazi-merchant/",
          }
        }
      },
      {
        type:"input",
        label:"名称1",
        prop:"name1",
        removeValidateUrl:"",
        placeholder:"请输入名称",
        defaultValue:"",
        required:true,
        switcher:[
          {
            prop:"sports",
            showValue:1
          }
        ],
        validate:{required:true,maxlength:15,minlength:1,number:"###.##",maxvalue:300.01,minvalue:100.00}
      },
      {
        type:"radio",
        label:"性别",
        prop:"sex",
        defaultValue:"0",
        switcher:[
          {
            prop:"sports",
            showValue:3
          }
        ],
        options:[
          {
            label:"男",
            value:"0"
          },
          {
            label:"女",
            value:"1"
          }
        ],
        placeholder:"请输入名称",
        required:true,
        validate:{watchers:true}
      },
      {
        type:"checkbox",
        label:"爱好",
        prop:"love",
        options:[
          {
            label:"看报",
            value:"0"
          },
          {
            label:"看电视",
            value:"1"
          },
          {
            label:"交友",
            value:"2"
          },
          {
            label:"创作",
            value:"3"
          }
        ],
        placeholder:"请输入名称",
        defaultValue:"",
        required:true,
        validate:{maxlength:5}
      },
      {
        type:"checkbox",
        label:"体育运动",
        prop:"sports",
        options:[
          {
            label:"跑步",
            value:"0"
          },
          {
            label:"健身",
            value:"1"
          },
          {
            label:"瑜伽",
            value:"2"
          },
          {
            label:"太极",
            value:"3"}
        ],
        placeholder:"请输入名称",
        defaultValue:"2",
        required:true,
        validate:{checkboxRequired:true,checkboxWatchers:true}
      },
      {
        type:"input",
        label:"内增高",
        switcher:[{
          prop:"sex",
          showValue:"1"
        }],
        prop:"innerHeight",
        validate:{required:true,number:"##.##",maxvalue:10,minvalue:0.5}
      },
      {
        type:"array",
        label:"活动时间",
        prop:"compSizeInnerHeight",
        options:[
          {
            label:"",
            type:"input",
            prop:"compA",
            required:true,
            value:"0"
          },
          {
            label:"至",
            type:"input",
            prop:"compB",
            value:"1"
          },
        ]
      },
      {
        label:"头像",
        prop:"photo",
        type:"upload",
        multiple:false,
        uploadClass:{myUploadStyle:true},
        imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
        validate:{required:true}
      },
      {
        label:"详情图片",
        prop:"detail",
        type:"upload",
        multiple:false,
        uploadClass:{myUploadStyle2:true},
        imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
        validate:{required:true}
      },
      {
        label:"商品详情图",
        type:"array",
        prop:"goodsDetailImages",
        validates:[],
        options:[
          {
            label:"",
            prop:"detailA",
            type:"upload",
            value:"",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailB",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailC",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          }
        ],
        validate:{arrayUploadRequired:3}
      }
    ]
  };

  submit(value:any){
    console.log("sub sub this.formGroup",value)
    this.baseDataService.listData({url:this.formModel.url,param:value,httpMethod:"post"}).subscribe((data:any)=>{
      console.log(data)
    },(error:any)=>{
      console.log(error);
      this.router.navigate(["lotteryList"])
    })
  }
}
