import {Component} from "@angular/core";
import {Router} from "@angular/router";
import {BaseDataService} from "angular-component-service";

@Component({
  selector:"create-goods-form",
  template:"<base-form-component [formModel]='formModel'></base-form-component>",
  providers:[BaseDataService]
})
export class CreateMerchantFormComponent{

  constructor(
    public baseDataService:BaseDataService,private router:Router
  ){
  }

  formModel:any={
    url:"goods/saveGoods.json",
    //washData:false,/*配置是否清洗数据结构 默认清洗除非需要全部数据明确指出不许清理*/
    submit:(value:any)=>{
      this.submit(value);
    },
    elements:[
      {
       type:"input",
       label:"店铺名称",
       prop:"goodsType",
       removeValidateUrl:"",
       placeholder:"请输入商品类型",
       defaultValue:"",
       required:true,
       validate:{required:true,maxlength:15}
       },
       {
       type:"radio",
       label:"服务区域",
       prop:"serviceRange",
       removeValidateUrl:"",
       placeholder:"商品发布范围",
       defaultValue:"2",
       required:true,
       options:[
       {label:"自动覆盖店铺",value:1},
       {label:"自定范围",value:2}
       ],
       switcher:[
       {
       prop:"goodsType",
       showValue:1
       }
       ],
       validate:{watchers:true}
       },
       {
       label:"选择服务范围",
       type:"baseAreaChoose",
       prop:"goodsServiceRangeDetail",
       defaultValue:"请输入商品服务范围",
       switcher:[
       {
       prop:"serviceRange",
       showValue:"2"
       }
       ]
       },
       {
       type:"select",
       label:"店铺类型",
       prop:"goodsCategory",
       defaultValue:"",
       remoteInfo:{
       baseUrl:"https://testbackend.goodaa.com.cn/ejiazi-backend/",
       url:"indexPromotion/initJumpTypes.json",
       httpMethod:"post",
       param:{name:"testName",promotionType:"1"},
       convert:(data:any)=>{
       let options=[
       {
       label:"请选择",
       value:""
       }
       ];
       if(data.code=="1"&&data.data){
       for(let key in data.data){
       options.push({
       label:data.data[key],
       value:key
       })
       }
       }
       return options;
       }
       },
       switcher:[
       {
       prop:"sports",
       showValue:3
       }
       ],
       options:[
       {
       label:"休闲食品",
       value:"0"
       },
       {
       label:"家居日化",
       value:"1"
       }
       ],
       placeholder:"请选择分类",
       required:true,
       validate:{watchers:true}
       },
       {
       type:"checkbox",
       label:"店铺标签",
       prop:"labels",
       options:[
       {
       label:"放心",
       value:"0"
       },
       {
       label:"专业",
       value:"1"
       },
       {
       label:"卫生",
       value:"2"
       },
       {
       label:"全面",
       value:"3"}
       ],
       placeholder:"请输入名称",
       defaultValue:"2",
       required:true,
       validate:{checkboxRequired:true,checkboxWatchers:true}
       },
       {
       type:"input",
       label:"一句话简评",
       prop:"shotJump",
       placeholder:"简要介绍",
       defaultValue:"",
       required:true,
       validate:{required:true,maxlength:5}
       },
       {
       type:"input",
       label:"门店地址",
       prop:"address",
       placeholder:"门店地址",
       defaultValue:"",
       required:true,
       validate:{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5}
       },
       {
       type:"input",
       label:"店铺简介",
       prop:"introduce",
       placeholder:"introduce",
       defaultValue:"",
       required:true,
       validate:{required:true}
       },
       {
       type:"checkbox",
       label:"售后说明",
       prop:"afterSale",
       options:[
       {
       label:"7天无理由退换",
       value:"0"
       }
       ],
       placeholder:"请输入名称",
       defaultValue:"2",
       required:true,
       validate:{checkboxWatchers:true}
       },
       {
       type:"input",
       label:"商品条码",
       switcher:[{
       prop:"sex",
       showValue:"1"
       }],
       prop:"goodsQurt",
       validate:{required:true,number:"##.##",maxvalue:10,minvalue:0.5}
       },
       {
       label:"店铺首图",
       prop:"firstPic",
       type:"upload",
       multiple:false,
       uploadClass:{myUploadStyle:true},
       require:true,
       defaultValue:"",
       imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
       validate:{required:true}
       },
      {
        label:"店铺宣传图",
        prop:"detailPics",
        type:"array",
        multiple:false,
        uploadClass:{myUploadStyle2:true},
        options:[
          {
            label:"",
            prop:"detailA",
            type:"upload",
            value:"",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailB",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailC",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailD",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailE",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailF",
            type:"upload",
            value:"",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailG",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailH",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailI",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          },
          {
            label:"",
            prop:"detailJ",
            value:"",
            type:"upload",
            multiple:false,
            uploadClass:{myUploadStyle2:true},
            imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
          }
        ],
        validate:{arrayUploadRequired:3}
      },
      {
       type:"radio",
       label:"合作形式",
       prop:"corpera",
       placeholder:"请输入商品名称",
       defaultValue:"1",
       options:[
       {
       label:"合作店铺",
       value:"0"
       },
       {
       label:"展示店铺",
       value:"1"
       }
       ],
       required:true,
       validates:{watchers:true}
       },
       {
       type:"input",
       label:"每人限购",
       prop:"buyLimitNum",
       placeholder:"请输入商品名称",
       defaultValue:"",
       required:true,
       switcher:[
       {
       prop:"isLimit",
       showValue:"0"
       }
       ],
       validate:{required:true,number:"###.##",maxvalue:"9999.99",minvalue:"0.01",maxlength:5}
       },
    ]
  };

  submit(value:any){
    console.log("sub sub this.formGroup",value)
    this.baseDataService.listData({url:this.formModel.url,param:value,httpMethod:"post"}).subscribe((data:any)=>{
      console.log(data)
    },(error:any)=>{
      console.log(error);
     // this.router.navigate(["lotteryList"])
    })
  }
}
