import {Component} from "@angular/core";
import {Router} from "@angular/router";
import {BaseValidateService} from "../../service/validate/base.validate.service";
import {BaseDataService} from "angular-component-service";
/**
 * Created by xkfeng on 2017/5/4.
 *
 * create goods  form
 *
 */


@Component({
  selector:"goods-from-create",
  template:"<base-form-component [formModel]='formModel'></base-form-component>",
  providers:[BaseDataService]
})
export class GoodsFormComponent{
  constructor(
    public baseDataService:BaseDataService,private router:Router
  ){
  }

  formModel:any={
  url:"goods/saveGoods.json",
  submit:(value:any)=>{
    this.submit(value);
  },
  elements:[
    {
      type:"input",
      label:"远程校验",
      prop:"name",
      removeValidateUrl:"",
      placeholder:"请输入名称",
      defaultValue:"",
      required:true,
      switcher:[{
        prop:"sports",
        showValue:2
      },{
        prop:"sex",
        showValue:0
      }],
      validate:{remote:true},
      override:{
        remoteValidateRequiredParam:{"name":true,name1:true},
        alias:{name:"inputName"},
        remoteService:{
          url:"goods/existName",
          httpMethod:"get",
          baseUrl:"https://testmerchant.goodaa.com.cn/ejiazi-merchant/",
        }
      }
    },
    {
      type:"input",
      label:"名称1",
      prop:"name1",
      removeValidateUrl:"",
      placeholder:"请输入名称",
      defaultValue:"",
      required:true,
      switcher:[
        {
          prop:"sports",
          showValue:1
        }
      ],
      validate:{required:true,maxlength:15,minlength:1,number:"###.##",maxvalue:300.01,minvalue:100.00}
    },
    {
      type:"radio",
      label:"性别",
      prop:"sex",
      defaultValue:"0",
      switcher:[
        {
          prop:"sports",
          showValue:3
        }
      ],
      options:[
        {
          label:"男",
          value:"0"
        },
        {
          label:"女",
          value:"1"
        }
      ],
      placeholder:"请输入名称",
      required:true,
      validate:{watchers:true}
    },
    {
      type:"checkbox",
      label:"爱好",
      prop:"love",
      options:[
        {
          label:"看报",
          value:"0"
        },
        {
          label:"看电视",
          value:"1"
        },
        {
          label:"交友",
          value:"2"
        },
        {
          label:"创作",
          value:"3"
        }
      ],
      placeholder:"请输入名称",
      defaultValue:"",
      required:true,
      validate:{maxlength:5}
    },
    {
      type:"checkbox",
      label:"体育运动",
      prop:"sports",
      options:[
        {
          label:"跑步",
          value:"0"
        },
        {
          label:"健身",
          value:"1"
        },
        {
          label:"瑜伽",
          value:"2"
        },
        {
          label:"太极",
          value:"3"}
      ],
      placeholder:"请输入名称",
      defaultValue:"2",
      required:true,
      validate:{checkboxRequired:true,checkboxWatchers:true}
    },
    {
      type:"input",
      label:"内增高",
      switcher:[{
        prop:"sex",
        showValue:"1"
      }],
      prop:"innerHeight",
      validate:{required:true,number:"##.##",maxvalue:10,minvalue:0.5}
    },
    {
      type:"array",
      label:"活动时间",
      prop:"compSizeInnerHeight",
      options:[
        {
          label:"",
          type:"input",
          prop:"compA",
          required:true,
          value:"0"
        },
        {
          label:"至",
          type:"input",
          prop:"compB",
          value:"1"
        },
      ]
    },
    {
      label:"头像",
      prop:"photo",
      type:"upload",
      multiple:false,
      uploadClass:{myUploadStyle:true},
      imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
      validate:{required:true}
    },
    {
      label:"详情图片",
      prop:"detail",
      type:"upload",
      multiple:false,
      uploadClass:{myUploadStyle2:true},
      imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"},
      validate:{required:true}
    },
    {
      label:"商品详情图",
      type:"array",
      prop:"goodsDetailImages",
      validates:[],
      options:[
        {
          label:"",
          prop:"detailA",
          type:"upload",
          value:"",
          multiple:false,
          uploadClass:{myUploadStyle2:true},
          imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
        },
        {
          label:"",
          prop:"detailB",
          value:"",
          type:"upload",
          multiple:false,
          uploadClass:{myUploadStyle2:true},
          imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
        },
        {
          label:"",
          prop:"detailC",
          value:"",
          type:"upload",
          multiple:false,
          uploadClass:{myUploadStyle2:true},
          imageConfig:{id:"imgId",url:"imageUrl",detail:"大转盘分享图标大小",size:"<30k","validate":true,extend:".png,.jpeg,.jpg"}
        }
      ],
      validate:{arrayUploadRequired:3}
    }
  ]
};

  submit(value:any){
    console.log("sub sub this.formGroup",value)
    this.baseDataService.listData({url:this.formModel.url,param:value,httpMethod:"post"}).subscribe((data:any)=>{
      console.log(data)
    },(error:any)=>{
      console.log(error);
      this.router.navigate(["lotteryList"])
    })
  }
}


